services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - "${JELLYFIN_PORT}:8096"
    volumes:
      - ../../config/jellyfin:/config
      - ${MEDIA_PATH}/Movies:/media/movies:ro
      - ${MEDIA_PATH}/TV:/media/tv:ro
      - ${MEDIA_PATH}/Anime:/media/anime:ro
    environment:
      - TZ=${TZ}
    networks:
      - media-net
    restart: unless-stopped

networks:
  media-net:
    external: true
