services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - "${QBITTORRENT_PORT}:8080"
      - "6881:6881/tcp"
      - "6881:6881/udp"
    volumes:
      - ../../config/qbittorrent:/config
      - ${TORRENTS_PATH}:/downloads
    environment:
      - TZ=${TZ}
    networks:
      - media-net
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - ../../config/sonarr:/config
      - ${MEDIA_PATH}/TV:/tv
      - ${TORRENTS_PATH}:/downloads
    environment:
      - TZ=${TZ}
    networks:
      - media-net
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - ../../config/radarr:/config
      - ${MEDIA_PATH}/Movies:/movies
      - ${TORRENTS_PATH}:/downloads
    environment:
      - TZ=${TZ}
    networks:
      - media-net
    restart: unless-stopped

networks:
  media-net:
    external: true